version: '3.8'

services:
  php_fpm:
    build: .
#    image: php:8.2-fpm
    ports:
      - "8080:80"
    volumes:
      - ./php:/var/www/html
    environment:
      - DB_HOST=mariadb
      - DB_NAME=mydatabase
      - DB_USER=myuser
      - DB_PASSWORD=mypassword
    networks:
      mynetwork:
        ipv4_address: 173.25.0.2

  nginx:
    image: nginx:1.21-alpine
    ports:
      - "85:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./php:/var/www/html
    depends_on:
      - php_fpm
    links:
      - php_fpm
      - rabbitmq
    networks:
      mynetwork:
        ipv4_address: 173.25.0.3

  mariadb:
    image: mariadb:10.5
    environment:
      - MYSQL_ROOT_PASSWORD=mypassword
      - MYSQL_DATABASE=mydatabase
      - MYSQL_USER=myuser
      - MYSQL_PASSWORD=mypassword
#    volumes:
#      - ./mariadb:/var/lib/mysql
    networks:
      mynetwork:
        ipv4_address: 173.25.0.4

  clickhouse:
    image: yandex/clickhouse-server:21.3
    ports:
      - "8123:8123"
#    volumes:
#      - ./clickhouse:/var/lib/clickhouse
    networks:
      mynetwork:
        ipv4_address: 173.25.0.5

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
#    volumes:
#      - ./rabbitmq:/var/lib/rabbitmq
    networks:
      mynetwork:
        ipv4_address: 173.25.0.6

networks:
  mynetwork:
    ipam:
      driver: default
      config:
        - subnet: 173.25.0.0/16